/// Flutter icons GoZAPPIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GoZAPPIcon
///      fonts:
///       - asset: fonts/GoZAPPIcon.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class GoZAPPIcon {
  GoZAPPIcon._();

  static const _kFontFam = 'GoZAPPIcon';
  static const String? _kFontPkg = null;

  static const IconData month_swaps = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recharged_swaps = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remaing_swaps = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData free_swaps = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asset = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asset_category_id = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asset_id = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment_type = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData returning_battery_id = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rider_id = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData service_type = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap_battery_id = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData admin_free_swaps = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData admin_paid_swaps = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData admin_recharge_swaps = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData admin_total_swaps = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
