/// Flutter icons GoZAPPIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GoZAPPIcon
///      fonts:
///       - asset: fonts/GoZAPPIcon.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class GoZAPPIcon {
  GoZAPPIcon._();

  static const _kFontFam = 'GoZAPPIcon';
  static const String? _kFontPkg = null;

  static const IconData month_swaps =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recharged_swaps =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remaing_swaps =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData free_swaps =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
